const ADD_TO_CART = "ADD_TO_CART";
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const DELETE_CART = "DELETE_CART";

export { ADD_TO_CART, INCREMENT, DECREMENT, REMOVE_FROM_CART, DELETE_CART };
